-- MySQL Script generated by MySQL Workbench
-- Fri May  3 00:00:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema shoppingMall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoppingMall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingMall` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_MEMBER_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_MEMBER_TB` (
  `MEMBER_IDX` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `MEMBER_ID` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `ADDR` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(15) NOT NULL,
  `PHONE_NUMBER1` VARCHAR(10) NOT NULL,
  `PHONE_NUMBER2` VARCHAR(10) NOT NULL,
  `PHONE_NUMBER3` VARCHAR(10) NOT NULL,
  `EMAIL1` VARCHAR(20) NOT NULL,
  `EMAIL2` VARCHAR(20) NOT NULL,
  `REG_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`MEMBER_IDX`),
  UNIQUE INDEX `MEMBER_ID_UNIQUE` (`MEMBER_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_ORDER_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_ORDER_TB` (
  `ORDER_ID` VARCHAR(50) NOT NULL,
  `MEMBER_IDX` VARCHAR(45) NULL DEFAULT NULL,
  `NON_MEMBER_IDX` VARCHAR(45) NULL DEFAULT NULL,
  `ADDR` VARCHAR(255) NULL,
  `PHONE_NUMBER1` VARCHAR(10) NOT NULL,
  `PHONE_NUMBER2` VARCHAR(10) NOT NULL,
  `PHONE_NUMBER3` VARCHAR(10) NOT NULL,
  `EMAIL1` VARCHAR(20) NOT NULL,
  `EMAIL2` VARCHAR(20) NOT NULL,
  `REG_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` TIMESTAMP NULL,
  PRIMARY KEY (`ORDER_ID`),
  INDEX `sh_member_tb_ibfk_1_idx` (`MEMBER_IDX` ASC),
  CONSTRAINT `sh_member_tb_ibfk_1`
    FOREIGN KEY (`MEMBER_IDX`)
    REFERENCES `shoppingMall`.`SH_MEMBER_TB` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_PRODUCT_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_PRODUCT_TB` (
  `PRODUCT_ID` VARCHAR(50) NOT NULL,
  `PRICE` INT(11) NOT NULL,
  `STATUS` ENUM('NOMAL', 'SOLDOUT', 'HIDDEN') NOT NULL DEFAULT 'HIDDEN',
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` TEXT NULL DEFAULT NULL,
  `MILEAGE` INT(11) UNSIGNED NULL DEFAULT '0',
  PRIMARY KEY (`PRODUCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`SH_ORDER_PROD_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SH_ORDER_PROD_TB` (
  `ORDER_ID` VARCHAR(50) NOT NULL,
  `PRODUCT_ID` VARCHAR(50) NOT NULL,
  `NUMBER` INT(10) NULL,
  `TYPE` ENUM('NORMAL', 'REFUND', 'SWAP') NULL DEFAULT 'NORMAL',
  PRIMARY KEY (`ORDER_ID`, `PRODUCT_ID`),
  INDEX `sh_product_tb_ibfk_1_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `sh_order_tb_ibfk_1`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `shoppingMall`.`SH_ORDER_TB` (`ORDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sh_product_tb_ibfk_1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `shoppingMall`.`SH_PRODUCT_TB` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `shoppingMall` ;

-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_BOARD_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_BOARD_TB` (
  `BOARD_IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `BOARD_TITLE` VARCHAR(200) NOT NULL,
  `BOARD_CONTENT` VARCHAR(4000) NULL DEFAULT NULL,
  `BOARD_WRITER` VARCHAR(50) NOT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `VIEW_COUNT` INT(11) NULL DEFAULT '0',
  `BOARD_SHOW` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`BOARD_IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_BOARD_ATTACH_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_BOARD_ATTACH_TB` (
  `BOARD_ATTACH_FULLNAME` VARCHAR(150) NOT NULL,
  `ATTACH_BOARD_IDX` INT(11) NOT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`BOARD_ATTACH_FULLNAME`),
  INDEX `ATTACH_BOARD_IDX` (`ATTACH_BOARD_IDX` ASC),
  CONSTRAINT `sh_board_attach_tb_ibfk_1`
    FOREIGN KEY (`ATTACH_BOARD_IDX`)
    REFERENCES `shoppingMall`.`SH_BOARD_TB` (`BOARD_IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_BOARD_REPLY_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_BOARD_REPLY_TB` (
  `REPLY_IDX` INT(11) NOT NULL AUTO_INCREMENT,
  `REPLY_BOARD_IDX` INT(11) NOT NULL,
  `REPLY_TEXT` VARCHAR(1000) NOT NULL,
  `REPLYER` VARCHAR(50) NULL DEFAULT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` TIMESTAMP NULL DEFAULT NULL,
  `SECRET_REPLY` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`REPLY_IDX`),
  INDEX `REPLY_BOARD_IDX` (`REPLY_BOARD_IDX` ASC),
  CONSTRAINT `sh_board_reply_tb_ibfk_1`
    FOREIGN KEY (`REPLY_BOARD_IDX`)
    REFERENCES `shoppingMall`.`SH_BOARD_TB` (`BOARD_IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_CATEGORY_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_CATEGORY_TB` (
  `CATEGORY_IDX` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ORDER_NO` INT(5) UNSIGNED NOT NULL DEFAULT -1,
  `NAME` VARCHAR(45) NOT NULL,
  `STATUS` ENUM('NORMAL', 'HIDDEN') NULL DEFAULT 'NORMAL',
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CATEGORY_IDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_CATEGORY_PRDT_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_CATEGORY_PRDT_TB` (
  `CATEGORY_IDX` INT(11) NOT NULL,
  `PRODUCT_ID` VARCHAR(50) NOT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CATEGORY_IDX`, `PRODUCT_ID`),
  INDEX `sh_product_tb_ibfk_1_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `sh_category_tb_ibfk_1`
    FOREIGN KEY (`CATEGORY_IDX`)
    REFERENCES `shoppingMall`.`SH_CATEGORY_TB` (`CATEGORY_IDX`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sh_product_tb_ibfk_1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `shoppingMall`.`SH_PRODUCT_TB` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_MILEAGE_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_MILEAGE_TB` (
  `MILEAGE_IDX` INT(10) UNSIGNED NOT NULL,
  `MEMBER_IDX` VARCHAR(45) NOT NULL,
  `INDECREASE_VAL` INT(11) NULL DEFAULT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`MILEAGE_IDX`),
  INDEX `sh_mileage_tb_ibfk_1_idx` (`MEMBER_IDX` ASC),
  CONSTRAINT `sh_mileage_tb_ibfk_1`
    FOREIGN KEY (`MEMBER_IDX`)
    REFERENCES `shoppingMall`.`SH_MEMBER_TB` (`MEMBER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_PRODUCT_OPTION_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_PRODUCT_OPTION_TB` (
  `PRDT_OPTION_IDX` INT(11) NOT NULL,
  `PRODUCT_ID` VARCHAR(45) NULL DEFAULT NULL,
  `NAME` VARCHAR(45) NOT NULL,
  `ADDED_PRICE` INT(11) NOT NULL,
  `HIDDEN` ENUM('Y', 'N') NOT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`PRDT_OPTION_IDX`),
  INDEX `sh_product_tb_ibfk_1_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `sh_product_tb_ibfk_1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `shoppingMall`.`SH_PRODUCT_TB` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shoppingMall`.`SH_RELATION_PRODUCT_TB`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingMall`.`SH_RELATION_PRODUCT_TB` (
  `RELATION_PRDT_IDX` INT(11) NOT NULL,
  `PRODUCT_ID` VARCHAR(50) NULL DEFAULT NULL,
  `REG_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`RELATION_PRDT_IDX`),
  INDEX `sh_product_tb_ibfk_1_idx` (`PRODUCT_ID` ASC),
  CONSTRAINT `sh_product_tb_ibfk_1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `shoppingMall`.`SH_PRODUCT_TB` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
